#
# ZSH environment by Joakim Tufvegren
#

# Set some standard variables
export PATH=$HOME/bin:$PATH:/usr/local/sbin:/usr/local/bin
export PAGER==less
export LESS="diRX"

[[ -x =vim ]] && export EDITOR="vim" || export EDITOR="vi"

# Fix backwards compatibility when using screen in some 256color terminals
[[ $TERM == "screen.xterm-256color" ]] && export TERM="screen-256color"

[[ $UID == $GID ]] && umask 002 || umask 022
