HISTSIZE=200
HISTFILE=~/.zsh_history
SAVEHIST=200

export PATH=$HOME/bin:$PATH:/usr/local/sbin:/usr/local/bin

export PAGER="$(echo =less)"

if [ -x =vim ]; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

# if $EDITOR begins with vi, ZSH goes into vi mode, and that's a bit too nerdy.
setopt emacs
