#
# ZSH environment by Joakim Andersson
#

# Set some standard variables
export PATH=$HOME/bin:$PATH:/usr/local/sbin:/usr/local/bin
export PAGER==less
[[ -x =vim ]] && export EDITOR="vim" || export EDITOR="vi"

[[ $UID == $GID ]] && umask 002 || umask 022
